### ISSUE TITLE
Some GNOME apps are almost completely transparent

### ISSUE THREAD

**Issue by Vistaus** [cyanut/elegant-brit#2]
It makes them unusable. For example, Nautilus and Clocks are affected by this bug.

OS: Ubuntu 16.04.x (latest)
GNOME Shell/GTK version: 3.20.1

**Comment by cyanut** [comment]
I just tested it in Ubuntu and it looked okay. Have you compiled the scss file? If not,  try running 
`scssc gtk-contained.scss gtk-contained.css` in the `gtk3.0` folder.

**Comment by Vistaus** [comment]
Oh, I didn't know about compiling the scss file. But I don't know what to install to obtain scssc 'cause when I run your command it says "command not found". libsass doesn't seem to contain scssc. So what package do I need to install?

**Comment by cyanut** [comment]
I pushed the compiled version into the repo if you want to take a look. Somehow on Ubuntu it doesn't look as good as I expected - so this just become a work in progress again :)

**Comment by Vistaus** [comment]
It works now! Thank you so much and keep up the good work! #ElegantBritFTW :smile:
